"""Generate standalone Kaggle entry points from the single maintained launcher."""
from pathlib import Path
import ast
import json
import sys


def main():
    root = Path(__file__).resolve().parents[1]
    sys.path.insert(0, str(root))
    # Read the pure configuration module without importing the training stack.
    import runpy
    preset = runpy.run_path(str(root / 'fed_learning/strategies/incremental/denice_variants.py'))['variant_preset']
    source = (root / 'train_incremental_kaggle.py').read_text(encoding='utf-8')
    launchers = [
        ('train_denice_der_kaggle.py', 'derpp', ('der', 'derpp')),
        ('train_denice_ewc_kaggle.py', 'ewc', ('ewc',)),
        ('train_denice_cgofed_kaggle.py', 'cgofed', ('cgofed',)),
    ]
    config_dir = root / 'configs'
    config_dir.mkdir(parents=True, exist_ok=True)
    for filename, variant, allowed in launchers:
        text = '# Generated by tools/build_denice_launchers.py; edit CONFIG/overrides or regenerate.\n' + source.replace(
            'import os\n', f'import os\nos.environ.setdefault("DENICE_VARIANT", "{variant}")\n'
            f'if os.environ["DENICE_VARIANT"].lower() not in {allowed!r}:\n'
            '    raise ValueError("DENICE_VARIANT conflicts with this launcher; use a fresh kernel or set it explicitly.")\n', 1)
        ast.parse(text)
        (root / filename).write_text(text, encoding='utf-8')
        (config_dir / ('denice_' + variant + '.json')).write_text(json.dumps(preset(variant), indent=2)+'\n', encoding='utf-8')
    (config_dir / 'denice_der.json').write_text(json.dumps(preset('der'), indent=2)+'\n', encoding='utf-8')


if __name__ == '__main__':
    main()
