"""Generate standalone Kaggle entry points from the single maintained launcher."""
from pathlib import Path
import ast
import json
import sys


def cgofed_smoke_launcher(text):
    """Add an optional bounded diagnostic run; default to full training."""
    text = text.replace('import os\n', 'import os\nCGOFED_SMOKE_TEST = False  # Full training; set True for the bounded smoke run.\n', 1)
    text = text.replace(
        'TRAIN_PHASE = int(os.environ.get("DENICE_TRAIN_PHASE", "5"))',
        'TRAIN_PHASE = 5 if CGOFED_SMOKE_TEST else int(os.environ.get("DENICE_TRAIN_PHASE", "5"))', 1)
    text = text.replace(
        '"DENICE_OUTPUT_DIR", f"/kaggle/working/results_denice_{TRAIN_VARIANT}_seed_{TRAIN_SEED}"',
        '"DENICE_OUTPUT_DIR", f"/kaggle/working/results_denice_{TRAIN_VARIANT}_seed_{TRAIN_SEED}"\n'
        '    + "_amp_only" + ("_smoke" if CGOFED_SMOKE_TEST else "")', 1)
    text = text.replace(
        '    CONFIG.update(variant_preset(TRAIN_VARIANT))',
        '    CONFIG.update(variant_preset(TRAIN_VARIANT))\n'
        '    CONFIG.update(denice_cgofed_peer_projection=False, denice_amp_enabled=True)', 1)
    marker = "if CONFIG.get('denice_cl_method', 'legacy') != 'legacy':"
    block = '''# Apply last so an old notebook override cannot turn the smoke run into full training.
if CGOFED_SMOKE_TEST:
    CONFIG.update({
        "task_start": 0,
        "task_end": 1,
        "rounds_per_task": 6,
        "denice_max_clients": 100,
        "denice_max_train_samples_per_client": 512,
        "denice_eval_max_clients": 5,
        "denice_eval_max_samples": 2000,
        "denice_eval_final_task_only": False,
        "denice_eval_final_round": False,
        "denice_post_task_eval_tasks": [1],
        "eval_every": 9999,
        "round_checkpoint_every": 1,
        "resume_state_path": None,
        "save_resume_after_task": None,
        "denice_amp_enabled": True,
    })
    print("CGOFED SMOKE TEST: fresh tasks 0-1, 6 rounds/task, up to 100 clients, max 512 training samples/client/task, AMP enabled.")

'''
    return text.replace(marker, block + marker, 1)


def main():
    root = Path(__file__).resolve().parents[1]
    sys.path.insert(0, str(root))
    # Read the pure configuration module without importing the training stack.
    import runpy
    preset = runpy.run_path(str(root / 'fed_learning/strategies/incremental/denice_variants.py'))['variant_preset']
    source = (root / 'train_incremental_kaggle.py').read_text(encoding='utf-8')
    launchers = [
        ('train_denice_der_kaggle.py', 'derpp', ('der', 'derpp')),
        ('train_denice_ewc_kaggle.py', 'ewc', ('ewc',)),
        ('train_denice_cgofed_kaggle.py', 'cgofed', ('cgofed',)),
    ]
    config_dir = root / 'configs'
    config_dir.mkdir(parents=True, exist_ok=True)
    for filename, variant, allowed in launchers:
        text = '# Generated by tools/build_denice_launchers.py; edit CONFIG/overrides or regenerate.\n' + source.replace(
            'import os\n', f'import os\nos.environ.setdefault("DENICE_VARIANT", "{variant}")\n'
            f'if os.environ["DENICE_VARIANT"].lower() not in {allowed!r}:\n'
            '    raise ValueError("DENICE_VARIANT conflicts with this launcher; use a fresh kernel or set it explicitly.")\n', 1)
        if variant == 'cgofed':
            text = cgofed_smoke_launcher(text)
        ast.parse(text)
        (root / filename).write_text(text, encoding='utf-8')
        (config_dir / ('denice_' + variant + '.json')).write_text(json.dumps(preset(variant), indent=2)+'\n', encoding='utf-8')
    (config_dir / 'denice_der.json').write_text(json.dumps(preset('der'), indent=2)+'\n', encoding='utf-8')


if __name__ == '__main__':
    main()
